# Generated by Django 2.1.7 on 2019-06-18 23:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0002_auto_20190508_2327'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='organization',
            options={},
        ),
    ]
