# Generated by Django 2.1.7 on 2019-06-25 09:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Activities', '0006_auto_20190625_0000'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sentence',
            name='artefactid',
            field=models.ForeignKey(blank=True, db_column='ArtefactID', null=True, on_delete=django.db.models.deletion.SET_NULL, to='Activities.Artefact', verbose_name='Artefacto'),
        ),
        migrations.AlterField(
            model_name='sentence',
            name='resourceid',
            field=models.ForeignKey(blank=True, db_column='ResourceID', null=True, on_delete=django.db.models.deletion.SET_NULL, to='Activities.Resource', verbose_name='Recurso'),
        ),
    ]
