# Generated by Django 2.1.7 on 2019-06-25 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Activities', '0007_auto_20190625_0904'),
    ]

    operations = [
        migrations.AddField(
            model_name='sentence',
            name='verb_sug',
            field=models.CharField(db_column='VerbSug', default=0, max_length=255, verbose_name='Verbo Sugerido'),
            preserve_default=False,
        ),
    ]
