# Generated by Django 2.1.7 on 2019-06-25 09:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Activities', '0008_sentence_verb_sug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sentence',
            name='verbid',
            field=models.ForeignKey(blank=True, db_column='VerbID', on_delete=django.db.models.deletion.DO_NOTHING, to='Activities.Verb', verbose_name='Verbo'),
        ),
    ]
