# Generated by Django 2.1.7 on 2019-06-25 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Activities', '0011_auto_20190625_0934'),
    ]

    operations = [
        migrations.AddField(
            model_name='sentence',
            name='art_sug',
            field=models.CharField(blank=True, db_column='ArtefactSug', max_length=255, verbose_name='Artefacto Sugerido'),
        ),
        migrations.AddField(
            model_name='sentence',
            name='resource_sug',
            field=models.CharField(blank=True, db_column='ResourceSug', max_length=255, verbose_name='Recurso Sugerido'),
        ),
    ]
