# Generated by Django 2.1.7 on 2019-06-25 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='description',
            field=models.TextField(max_length=500),
        ),
        migrations.AlterField(
            model_name='process',
            name='description',
            field=models.TextField(max_length=500),
        ),
        migrations.AlterField(
            model_name='role',
            name='description',
            field=models.TextField(max_length=500),
        ),
    ]
