# Generated by Django 2.1.7 on 2019-04-24 15:56

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('processes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='role',
            name='product',
            field=models.ManyToManyField(to='processes.Product'),
        ),
        migrations.AlterField(
            model_name='process',
            name='creation_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 4, 24, 15, 56, 25, 253736, tzinfo=utc), verbose_name='date created'),
        ),
    ]
