# Generated by Django 2.1.7 on 2019-06-26 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processes', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='activity',
        ),
        migrations.AddField(
            model_name='activity',
            name='product',
            field=models.ManyToManyField(blank=True, to='processes.Product'),
        ),
    ]
