# Generated by Django 2.1.7 on 2019-04-24 15:57

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('processes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='process',
            name='creation_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 4, 24, 15, 57, 41, 30763, tzinfo=utc), verbose_name='date created'),
        ),
    ]
