# Generated by Django 2.1.7 on 2019-06-26 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processes', '0002_auto_20190626_0507'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activity',
            name='product',
        ),
        migrations.AddField(
            model_name='product',
            name='activity',
            field=models.ManyToManyField(blank=True, to='processes.Activity'),
        ),
    ]
