# Generated by Django 2.1.7 on 2019-04-24 16:10

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('processes', '0002_auto_20190424_1656'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='role',
            name='activity',
        ),
        migrations.AddField(
            model_name='activity',
            name='role',
            field=models.ManyToManyField(to='processes.Role'),
        ),
        migrations.AlterField(
            model_name='process',
            name='creation_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 4, 24, 16, 10, 44, 957040, tzinfo=utc), verbose_name='date created'),
        ),
    ]
