# Generated by Django 2.1.7 on 2019-04-24 16:25

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('processes', '0003_auto_20190424_1710'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='activity',
            field=models.ManyToManyField(to='processes.Activity'),
        ),
        migrations.AlterField(
            model_name='process',
            name='creation_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 4, 24, 16, 25, 32, 3490, tzinfo=utc), verbose_name='date created'),
        ),
    ]
