# Generated by Django 2.1.7 on 2019-06-26 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processes', '0004_auto_20190626_0742'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='description',
            field=models.TextField(max_length=400),
        ),
        migrations.AlterField(
            model_name='process',
            name='description',
            field=models.TextField(max_length=400),
        ),
        migrations.AlterField(
            model_name='role',
            name='description',
            field=models.TextField(max_length=300),
        ),
    ]
