# Generated by Django 2.1.7 on 2019-04-29 14:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('processes', '0005_auto_20190424_1733'),
        ('processes', '0002_auto_20190424_1657'),
    ]

    operations = [
    ]
