# Generated by Django 2.1.7 on 2019-04-29 14:53

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('processes', '0006_merge_20190429_1553'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='role',
            field=models.ManyToManyField(blank=True, to='processes.Role'),
        ),
        migrations.AlterField(
            model_name='process',
            name='creation_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 4, 29, 14, 53, 52, 686434, tzinfo=utc), verbose_name='date created'),
        ),
        migrations.AlterField(
            model_name='role',
            name='product',
            field=models.ManyToManyField(blank=True, to='processes.Product'),
        ),
    ]
