# Generated by Django 2.1.7 on 2019-06-26 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processes', '0006_auto_20190626_0744'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='procduct_input',
            field=models.CharField(default='input for dummies', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='product_output',
            field=models.CharField(default='output for dummies', max_length=200),
            preserve_default=False,
        ),
    ]
