# Generated by Django 2.1.7 on 2019-06-26 07:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('processes', '0007_auto_20190626_0809'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='procduct_input',
            new_name='product_input',
        ),
    ]
