# Generated by Django 2.1.7 on 2019-05-08 12:14

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('processes', '0007_auto_20190429_1553'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activity',
            name='process',
        ),
        migrations.AddField(
            model_name='activity',
            name='process',
            field=models.ManyToManyField(blank=True, null=True, to='processes.Process'),
        ),
        migrations.AlterField(
            model_name='process',
            name='creation_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 5, 8, 12, 14, 41, 6711, tzinfo=utc), verbose_name='date created'),
        ),
    ]
