# Generated by Django 2.1.7 on 2019-05-08 22:27

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('processes', '0008_auto_20190508_1314'),
    ]

    operations = [
        migrations.RenameField(
            model_name='process',
            old_name='user',
            new_name='userid',
        ),
        migrations.AlterField(
            model_name='process',
            name='creation_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 5, 8, 22, 27, 22, 367543, tzinfo=utc), verbose_name='date created'),
        ),
    ]
