# Generated by Django 2.1.7 on 2019-05-10 17:03

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('processes', '0010_auto_20190508_2329'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activity',
            name='process',
        ),
        migrations.AddField(
            model_name='activity',
            name='process',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='processes.Process'),
        ),
        migrations.AlterField(
            model_name='process',
            name='creation_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 5, 10, 17, 3, 13, 946383, tzinfo=utc), verbose_name='date created'),
        ),
    ]
