# Generated by Django 2.1.7 on 2019-05-10 17:16

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('processes', '0011_auto_20190510_1803'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activity',
            name='process',
        ),
        migrations.AddField(
            model_name='activity',
            name='process',
            field=models.ManyToManyField(blank=True, to='processes.Process'),
        ),
        migrations.AlterField(
            model_name='process',
            name='creation_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 5, 10, 17, 16, 1, 705237, tzinfo=utc), verbose_name='date created'),
        ),
    ]
