# Generated by Django 2.1.7 on 2019-05-15 14:33

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('processes', '0012_auto_20190510_1816'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='activity',
            options={'verbose_name': 'Activity'},
        ),
        migrations.RemoveField(
            model_name='activity',
            name='process',
        ),
        migrations.AddField(
            model_name='activity',
            name='process',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='processes.Process'),
        ),
        migrations.AlterField(
            model_name='process',
            name='creation_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 5, 15, 14, 33, 52, 954830, tzinfo=utc), verbose_name='date created'),
        ),
    ]
