# Generated by Django 2.1.7 on 2019-05-15 16:46

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('processes', '0013_auto_20190515_1533'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='original',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='processes.Activity'),
        ),
        migrations.AlterField(
            model_name='process',
            name='creation_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 5, 15, 16, 46, 8, 852554, tzinfo=utc), verbose_name='date created'),
        ),
    ]
