# Generated by Django 2.1.7 on 2019-05-21 14:04

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Activities', '0001_initial'),
        ('processes', '0014_auto_20190515_1746'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='pattern',
            field=models.ManyToManyField(to='Activities.Pattern'),
        ),
        migrations.AlterField(
            model_name='process',
            name='creation_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 5, 21, 14, 4, 54, 781021, tzinfo=utc), verbose_name='date created'),
        ),
    ]
