# Generated by Django 2.1.7 on 2019-05-23 14:43

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('processes', '0015_auto_20190521_1504'),
    ]

    operations = [
        migrations.AlterField(
            model_name='process',
            name='creation_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 5, 23, 14, 43, 20, 970728, tzinfo=utc), verbose_name='date created'),
        ),
    ]
