# Generated by Django 2.1.7 on 2019-05-24 14:43

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('processes', '0017_auto_20190524_1542'),
    ]

    operations = [
        migrations.AlterField(
            model_name='process',
            name='creation_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 5, 24, 14, 43, 57, 162038, tzinfo=utc), verbose_name='date created'),
        ),
    ]
