# Generated by Django 2.1.7 on 2019-06-22 12:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('processes', '0022_auto_20190619_0054'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='role',
            name='product',
        ),
    ]
