# Generated by Django 2.1.7 on 2019-03-26 21:07

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20190326_2105'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='process',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.Process'),
        ),
        migrations.AlterField(
            model_name='post',
            name='published',
            field=models.DateTimeField(default=datetime.datetime(2019, 3, 26, 21, 7, 0, 451048, tzinfo=utc), verbose_name='date published'),
        ),
        migrations.AlterField(
            model_name='process',
            name='creation_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 3, 26, 21, 7, 0, 451048, tzinfo=utc), verbose_name='date created'),
        ),
        migrations.AlterField(
            model_name='tutorial',
            name='tutorial_published',
            field=models.DateTimeField(default=datetime.datetime(2019, 3, 26, 21, 7, 0, 453003, tzinfo=utc), verbose_name='date published'),
        ),
    ]
