# Generated by Django 2.1.7 on 2019-04-02 19:46

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_auto_20190327_2206'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'permissions': (('test_GProc', 'Teste de permissao geral Gestor de Processos'), ('test_Analist', 'Teste de permissao geral Analista'), ('test_Func', 'Teste de permissao geral Funcionário'), ('test_Admin', 'Teste de permissao geral Administrador'))},
        ),
        migrations.AlterField(
            model_name='post',
            name='published',
            field=models.DateTimeField(default=datetime.datetime(2019, 4, 2, 19, 46, 45, 414953, tzinfo=utc), verbose_name='date published'),
        ),
        migrations.AlterField(
            model_name='process',
            name='creation_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 4, 2, 19, 46, 45, 414953, tzinfo=utc), verbose_name='date created'),
        ),
    ]
