# Generated by Django 2.1.7 on 2019-04-04 19:25

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_auto_20190402_2046'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='user_profile',
            new_name='profile',
        ),
        migrations.AlterField(
            model_name='post',
            name='published',
            field=models.DateTimeField(default=datetime.datetime(2019, 4, 4, 19, 24, 59, 992421, tzinfo=utc), verbose_name='date published'),
        ),
        migrations.AlterField(
            model_name='process',
            name='creation_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 4, 4, 19, 24, 59, 992421, tzinfo=utc), verbose_name='date created'),
        ),
    ]
