# Generated by Django 2.1.7 on 2019-04-07 00:28

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_auto_20190404_2025'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='published',
            field=models.DateTimeField(default=datetime.datetime(2019, 4, 7, 0, 28, 44, 153949, tzinfo=utc), verbose_name='date published'),
        ),
        migrations.AlterField(
            model_name='process',
            name='creation_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 4, 7, 0, 28, 44, 153949, tzinfo=utc), verbose_name='date created'),
        ),
    ]
