# Generated by Django 2.1.7 on 2019-04-07 00:34

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_auto_20190407_0128'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='published',
            field=models.DateTimeField(default=datetime.datetime(2019, 4, 7, 0, 34, 13, 796857, tzinfo=utc), verbose_name='date published'),
        ),
        migrations.AlterField(
            model_name='process',
            name='creation_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 4, 7, 0, 34, 13, 796857, tzinfo=utc), verbose_name='date created'),
        ),
    ]
