# Generated by Django 2.1.7 on 2019-04-07 16:51

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_auto_20190407_0134'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='Organization',
            new_name='organization',
        ),
        migrations.AlterField(
            model_name='post',
            name='published',
            field=models.DateTimeField(default=datetime.datetime(2019, 4, 7, 16, 51, 7, 296428, tzinfo=utc), verbose_name='date published'),
        ),
        migrations.AlterField(
            model_name='process',
            name='creation_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 4, 7, 16, 51, 7, 296428, tzinfo=utc), verbose_name='date created'),
        ),
    ]
