# Generated by Django 2.1.7 on 2019-04-07 17:30

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0016_auto_20190407_1801'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile', models.CharField(default='Funcionario', max_length=100)),
                ('Organization', models.ForeignKey(default='None', on_delete=django.db.models.deletion.SET_DEFAULT, to='main.Organization')),
                ('user', models.OneToOneField(on_delete='cascade', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'permissions': (('test_GProc', 'Teste de permissao geral Gestor de Processos'), ('test_Analist', 'Teste de permissao geral Analista'), ('test_Func', 'Teste de permissao geral Funcionário'), ('test_Admin', 'Teste de permissao geral Administrador')),
            },
        ),
        migrations.RemoveField(
            model_name='employee',
            name='organization',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='user',
        ),
        migrations.AlterField(
            model_name='post',
            name='published',
            field=models.DateTimeField(default=datetime.datetime(2019, 4, 7, 17, 30, 47, 560530, tzinfo=utc), verbose_name='date published'),
        ),
        migrations.AlterField(
            model_name='process',
            name='creation_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 4, 7, 17, 30, 47, 560530, tzinfo=utc), verbose_name='date created'),
        ),
        migrations.DeleteModel(
            name='Employee',
        ),
    ]
